-- Supabase bootstrap schema for JNPI services
-- Generated from current SQLite schemas in services/*/storage
-- Updated to reflect multimodal chunking (page image + extracted text)
-- Date: 2026-03-23
-- Version: Standard SQL (No "IF NOT EXISTS")

begin;

-- Keep all tables in public for simplest migration path.
-- You can later split into schemas (knowledge, workflow, governance, agent) if desired.

-- -----------------------------------------------------------------------------
-- knowledge-service
-- -----------------------------------------------------------------------------
create table public.sources (
    source_id text primary key,
    source_name text not null,
    filename text not null,
    file_type text not null,
    doc_type text not null default 'general',
    tags jsonb not null default '[]'::jsonb,
    language text not null default 'auto',
    visibility text not null default 'public',
    approval_status text not null default 'approved',
    date_of_the_constitution text,
    ministry_type text not null default 'general',
    metadata jsonb not null default '{}'::jsonb,
    current_version integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.chunks (
    chunk_id text primary key,
    source_id text not null references public.sources(source_id) on delete cascade,
    version integer not null,
    page integer not null,
    chunk_type text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table public.versions (
    id bigint generated by default as identity primary key,
    source_id text not null references public.sources(source_id) on delete cascade,
    version integer not null,
    chunks_created integer not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    unique (source_id, version)
);

create table public.file_hashes (
    hash text primary key,
    source_id text not null references public.sources(source_id) on delete cascade,
    version integer not null,
    filename text not null,
    created_at timestamptz not null default now()
);

create index idx_chunks_source on public.chunks(source_id);
create index idx_chunks_version on public.chunks(source_id, version);
create index idx_chunks_type on public.chunks(chunk_type);
create index idx_chunks_source_page on public.chunks(source_id, page);
create index idx_versions_source on public.versions(source_id);
create index idx_sources_visibility on public.sources(visibility);
create index idx_sources_approval on public.sources(approval_status);

-- -----------------------------------------------------------------------------
-- workflow-service
-- -----------------------------------------------------------------------------
create table public.cases (
    case_id text primary key,
    request_id text not null,
    session_id text,
    user_id text,
    query text not null,
    query_hash text not null,
    user_type text not null default 'citizen',
    sector_primary text not null default 'general',
    sector_labels jsonb not null default '[]'::jsonb,
    priority text not null default 'medium',
    status text not null default 'open',
    assigned_to text,
    escalation_reason text not null,
    confidence double precision,
    source_response_id text,
    resolution_answer text,
    resolution_note text,
    is_faq_candidate boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    resolved_at timestamptz
);

create table public.case_timeline (
    id bigint generated by default as identity primary key,
    case_id text not null references public.cases(case_id) on delete cascade,
    event_type text not null,
    actor text not null,
    note text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index idx_cases_status on public.cases(status);
create index idx_cases_sector on public.cases(sector_primary);
create index idx_cases_assigned on public.cases(assigned_to);
create index idx_cases_user on public.cases(user_id);
create index idx_cases_created on public.cases(created_at);
create index idx_cases_request on public.cases(request_id);
create index idx_timeline_case on public.case_timeline(case_id);

-- -----------------------------------------------------------------------------
-- governance-service
-- -----------------------------------------------------------------------------
create table public.audit_log (
    id bigint generated by default as identity primary key,
    request_id text not null unique,
    session_id text,
    query text not null,
    user_type text not null default 'citizen',
    intent text,
    sector text,
    agent_used text,
    answer text,
    confidence double precision,
    has_amendments boolean not null default false,
    escalated boolean not null default false,
    escalation_reason text,
    input_passed boolean not null default true,
    input_category text,
    input_reason text,
    output_passed boolean not null default true,
    output_category text,
    output_reason text,
    total_latency_ms double precision,
    routing_latency_ms double precision,
    retrieval_latency_ms double precision,
    generation_latency_ms double precision,
    citations_count integer not null default 0,
    chunks_used integer not null default 0,
    created_at timestamptz not null default now()
);

create index idx_audit_session on public.audit_log(session_id);
create index idx_audit_created on public.audit_log(created_at);
create index idx_audit_user_type on public.audit_log(user_type);
create index idx_audit_sector on public.audit_log(sector);
create index idx_audit_escalated on public.audit_log(escalated);
create index idx_audit_input_passed on public.audit_log(input_passed);
create index idx_audit_output_passed on public.audit_log(output_passed);

-- -----------------------------------------------------------------------------
-- agent-service
-- -----------------------------------------------------------------------------
create table public.sessions (
    session_id text primary key,
    messages jsonb not null default '[]'::jsonb,
    user_type text not null default 'citizen',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index idx_sessions_updated_at on public.sessions(updated_at);

-- -----------------------------------------------------------------------------
-- Optional pgvector extension/table for phase-2 vector migration
-- -----------------------------------------------------------------------------
create extension vector;

-- NOTE: Set vector dimension to match EMBEDDING_DIMENSIONS in runtime env.
-- Current service template uses 768; change to 3072 if you run full-size vectors.
create table public.chunk_embeddings (
    chunk_id text primary key references public.chunks(chunk_id) on delete cascade,
    source_id text not null references public.sources(source_id) on delete cascade,
    version integer not null,
    page integer not null,
    chunk_type text not null,
    modality text not null,
    page_key text,
    metadata jsonb not null default '{}'::jsonb,
    embedding vector(768) not null,
    created_at timestamptz not null default now()
);

create index idx_chunk_embeddings_source
    on public.chunk_embeddings(source_id, version);

create index idx_chunk_embeddings_page
    on public.chunk_embeddings(source_id, page);

create index idx_chunk_embeddings_type
    on public.chunk_embeddings(chunk_type, modality);

create index idx_chunk_embeddings_page_key
    on public.chunk_embeddings(page_key)
    where page_key is not null;

create index idx_chunk_embeddings_ivfflat
    on public.chunk_embeddings using ivfflat (embedding vector_cosine_ops)
    with (lists = 100);

commit;
