"""
Governance Service Database
Supports SQLite (default) and Supabase Postgres (optional).
"""
import sqlite3
from datetime import datetime, timezone, timedelta
from pathlib import Path

from config import AUDIT_RETENTION_DAYS, DATABASE_URL, DB_PATH, USE_SUPABASE

try:
    import psycopg
    from psycopg.rows import dict_row
except Exception:  # pragma: no cover
    psycopg = None
    dict_row = None


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


class Database:
    """Store for governance data backed by SQLite or Postgres."""

    def __init__(self, db_path: Path = DB_PATH):
        self.db_path = db_path
        self.use_supabase = USE_SUPABASE
        self.database_url = DATABASE_URL

        if self.use_supabase:
            if not self.database_url:
                raise RuntimeError("USE_SUPABASE=true but DATABASE_URL is empty")
            if psycopg is None:
                raise RuntimeError("psycopg is required when USE_SUPABASE=true")
        self._init_db()

    def _conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(str(self.db_path))
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA foreign_keys=ON")
        return conn

    def _pg_conn(self):
        url = self.database_url
        if "sslmode=" not in url:
            url = f"{url}?sslmode=require" if "?" not in url else f"{url}&sslmode=require"
        return psycopg.connect(url, row_factory=dict_row)

    def _init_db(self):
        if self.use_supabase:
            self._init_postgres()
            return

        with self._conn() as conn:
            conn.executescript("""
                CREATE TABLE IF NOT EXISTS audit_log (
                    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
                    request_id          TEXT NOT NULL UNIQUE,
                    session_id          TEXT,
                    query               TEXT NOT NULL,
                    user_type           TEXT NOT NULL DEFAULT 'citizen',
                    intent              TEXT,
                    sector              TEXT,
                    agent_used          TEXT,
                    answer              TEXT,
                    confidence          REAL,
                    has_amendments      INTEGER DEFAULT 0,
                    escalated           INTEGER DEFAULT 0,
                    escalation_reason   TEXT,
                    input_passed        INTEGER DEFAULT 1,
                    input_category      TEXT,
                    input_reason        TEXT,
                    output_passed       INTEGER DEFAULT 1,
                    output_category     TEXT,
                    output_reason       TEXT,
                    total_latency_ms    REAL,
                    routing_latency_ms  REAL,
                    retrieval_latency_ms REAL,
                    generation_latency_ms REAL,
                    citations_count     INTEGER DEFAULT 0,
                    chunks_used         INTEGER DEFAULT 0,
                    created_at          TEXT NOT NULL
                );

                CREATE INDEX IF NOT EXISTS idx_audit_session ON audit_log(session_id);
                CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);
                CREATE INDEX IF NOT EXISTS idx_audit_user_type ON audit_log(user_type);
                CREATE INDEX IF NOT EXISTS idx_audit_sector ON audit_log(sector);
                CREATE INDEX IF NOT EXISTS idx_audit_escalated ON audit_log(escalated);
                CREATE INDEX IF NOT EXISTS idx_audit_input_passed ON audit_log(input_passed);
                CREATE INDEX IF NOT EXISTS idx_audit_output_passed ON audit_log(output_passed);
            """)

    def _init_postgres(self):
        with self._pg_conn() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS audit_log (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        request_id TEXT NOT NULL UNIQUE,
                        session_id TEXT,
                        query TEXT NOT NULL,
                        user_type TEXT NOT NULL DEFAULT 'citizen',
                        intent TEXT,
                        sector TEXT,
                        agent_used TEXT,
                        answer TEXT,
                        confidence DOUBLE PRECISION,
                        has_amendments BOOLEAN NOT NULL DEFAULT FALSE,
                        escalated BOOLEAN NOT NULL DEFAULT FALSE,
                        escalation_reason TEXT,
                        input_passed BOOLEAN NOT NULL DEFAULT TRUE,
                        input_category TEXT,
                        input_reason TEXT,
                        output_passed BOOLEAN NOT NULL DEFAULT TRUE,
                        output_category TEXT,
                        output_reason TEXT,
                        total_latency_ms DOUBLE PRECISION,
                        routing_latency_ms DOUBLE PRECISION,
                        retrieval_latency_ms DOUBLE PRECISION,
                        generation_latency_ms DOUBLE PRECISION,
                        citations_count INTEGER NOT NULL DEFAULT 0,
                        chunks_used INTEGER NOT NULL DEFAULT 0,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                    );
                    """
                )
                cur.execute("CREATE INDEX IF NOT EXISTS idx_audit_session ON audit_log(session_id)")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at)")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_audit_user_type ON audit_log(user_type)")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_audit_sector ON audit_log(sector)")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_audit_escalated ON audit_log(escalated)")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_audit_input_passed ON audit_log(input_passed)")
                cur.execute("CREATE INDEX IF NOT EXISTS idx_audit_output_passed ON audit_log(output_passed)")
            conn.commit()

    # ─── Audit CRUD ───────────────────────────────────────────────────

    def insert_audit(self, entry: dict) -> int:
        """Insert an audit log entry. Returns the row id."""
        now = _now()

        if self.use_supabase:
            with self._pg_conn() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        """INSERT INTO audit_log (
                            request_id, session_id, query, user_type, intent, sector,
                            agent_used, answer, confidence, has_amendments, escalated,
                            escalation_reason, input_passed, input_category, input_reason,
                            output_passed, output_category, output_reason,
                            total_latency_ms, routing_latency_ms, retrieval_latency_ms,
                            generation_latency_ms, citations_count, chunks_used, created_at
                        ) VALUES (
                            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                        ) RETURNING id""",
                        (
                            entry["request_id"], entry.get("session_id"),
                            entry["query"], entry.get("user_type", "citizen"),
                            entry.get("intent"), entry.get("sector"),
                            entry.get("agent_used"), entry.get("answer"),
                            entry.get("confidence"),
                            bool(entry.get("has_amendments", False)),
                            bool(entry.get("escalated", False)),
                            entry.get("escalation_reason"),
                            bool(entry.get("input_passed", True)),
                            entry.get("input_category"), entry.get("input_reason"),
                            bool(entry.get("output_passed", True)),
                            entry.get("output_category"), entry.get("output_reason"),
                            entry.get("total_latency_ms"), entry.get("routing_latency_ms"),
                            entry.get("retrieval_latency_ms"), entry.get("generation_latency_ms"),
                            entry.get("citations_count", 0), entry.get("chunks_used", 0),
                            now,
                        ),
                    )
                    row_id = cur.fetchone()["id"]
                conn.commit()
                return int(row_id)

        with self._conn() as conn:
            cursor = conn.execute(
                """INSERT INTO audit_log (
                    request_id, session_id, query, user_type, intent, sector,
                    agent_used, answer, confidence, has_amendments, escalated,
                    escalation_reason, input_passed, input_category, input_reason,
                    output_passed, output_category, output_reason,
                    total_latency_ms, routing_latency_ms, retrieval_latency_ms,
                    generation_latency_ms, citations_count, chunks_used, created_at
                ) VALUES (
                    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
                )""",
                (
                    entry["request_id"], entry.get("session_id"),
                    entry["query"], entry.get("user_type", "citizen"),
                    entry.get("intent"), entry.get("sector"),
                    entry.get("agent_used"), entry.get("answer"),
                    entry.get("confidence"),
                    int(entry.get("has_amendments", False)),
                    int(entry.get("escalated", False)),
                    entry.get("escalation_reason"),
                    int(entry.get("input_passed", True)),
                    entry.get("input_category"), entry.get("input_reason"),
                    int(entry.get("output_passed", True)),
                    entry.get("output_category"), entry.get("output_reason"),
                    entry.get("total_latency_ms"), entry.get("routing_latency_ms"),
                    entry.get("retrieval_latency_ms"), entry.get("generation_latency_ms"),
                    entry.get("citations_count", 0), entry.get("chunks_used", 0),
                    now,
                )
            )
        return cursor.lastrowid

    def get_audit(self, request_id: str) -> dict | None:
        """Get a single audit record by request_id."""
        if self.use_supabase:
            with self._pg_conn() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        "SELECT * FROM audit_log WHERE request_id = %s", (request_id,)
                    )
                    row = cur.fetchone()
            return dict(row) if row else None

        with self._conn() as conn:
            row = conn.execute(
                "SELECT * FROM audit_log WHERE request_id = ?", (request_id,)
            ).fetchone()
        if row is None:
            return None
        return dict(row)

    def query_audit(self, filters: dict) -> tuple[list[dict], int]:
        """
        Query audit logs with filters. Returns (records, total_count).
        Supported filters: session_id, user_type, sector, escalated,
        input_passed, output_passed, date_from, date_to, page, page_size.
        """
        conditions = []
        params = []

        if filters.get("session_id"):
            conditions.append("session_id = ?")
            params.append(filters["session_id"])
        if filters.get("user_type"):
            conditions.append("user_type = ?")
            params.append(filters["user_type"])
        if filters.get("sector"):
            conditions.append("sector = ?")
            params.append(filters["sector"])
        if filters.get("escalated") is not None:
            conditions.append("escalated = ?")
            params.append(int(filters["escalated"]))
        if filters.get("input_passed") is not None:
            conditions.append("input_passed = ?")
            params.append(int(filters["input_passed"]))
        if filters.get("output_passed") is not None:
            conditions.append("output_passed = ?")
            params.append(int(filters["output_passed"]))
        if filters.get("date_from"):
            conditions.append("created_at >= ?")
            params.append(filters["date_from"])
        if filters.get("date_to"):
            conditions.append("created_at <= ?")
            params.append(filters["date_to"])

        where = " AND ".join(conditions) if conditions else "1=1"
        page = filters.get("page", 1)
        page_size = filters.get("page_size", 50)
        offset = (page - 1) * page_size

        if self.use_supabase:
            pg_conditions = []
            pg_params = []

            if filters.get("session_id"):
                pg_conditions.append("session_id = %s")
                pg_params.append(filters["session_id"])
            if filters.get("user_type"):
                pg_conditions.append("user_type = %s")
                pg_params.append(filters["user_type"])
            if filters.get("sector"):
                pg_conditions.append("sector = %s")
                pg_params.append(filters["sector"])
            if filters.get("escalated") is not None:
                pg_conditions.append("escalated = %s")
                pg_params.append(bool(filters["escalated"]))
            if filters.get("input_passed") is not None:
                pg_conditions.append("input_passed = %s")
                pg_params.append(bool(filters["input_passed"]))
            if filters.get("output_passed") is not None:
                pg_conditions.append("output_passed = %s")
                pg_params.append(bool(filters["output_passed"]))
            if filters.get("date_from"):
                pg_conditions.append("created_at >= %s")
                pg_params.append(filters["date_from"])
            if filters.get("date_to"):
                pg_conditions.append("created_at <= %s")
                pg_params.append(filters["date_to"])

            pg_where = " AND ".join(pg_conditions) if pg_conditions else "1=1"

            with self._pg_conn() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        f"SELECT COUNT(*) AS cnt FROM audit_log WHERE {pg_where}",
                        pg_params,
                    )
                    total = int(cur.fetchone()["cnt"])

                    cur.execute(
                        f"SELECT * FROM audit_log WHERE {pg_where} ORDER BY created_at DESC LIMIT %s OFFSET %s",
                        pg_params + [page_size, offset],
                    )
                    rows = cur.fetchall()

            return [dict(r) for r in rows], total

        with self._conn() as conn:
            total = conn.execute(
                f"SELECT COUNT(*) FROM audit_log WHERE {where}", params
            ).fetchone()[0]

            rows = conn.execute(
                f"SELECT * FROM audit_log WHERE {where} ORDER BY created_at DESC LIMIT ? OFFSET ?",
                params + [page_size, offset]
            ).fetchall()

        return [dict(r) for r in rows], total

    def list_audit_window(self, date_from: str, date_to: str | None = None, limit: int = 20000) -> list[dict]:
        """Return recent audit records in a time window ordered by created_at ascending."""
        safe_limit = max(100, min(int(limit or 20000), 50000))

        if self.use_supabase:
            conditions = ["created_at >= %s"]
            params: list = [date_from]
            if date_to:
                conditions.append("created_at < %s")
                params.append(date_to)
            where_sql = " AND ".join(conditions)

            with self._pg_conn() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        f"""
                        SELECT request_id, query, sector, confidence, escalated,
                               input_passed, output_passed, total_latency_ms, created_at
                        FROM audit_log
                        WHERE {where_sql}
                        ORDER BY created_at ASC
                        LIMIT %s
                        """,
                        params + [safe_limit],
                    )
                    rows = cur.fetchall()
            return [dict(r) for r in rows]

        conditions = ["created_at >= ?"]
        params = [date_from]
        if date_to:
            conditions.append("created_at < ?")
            params.append(date_to)
        where_sql = " AND ".join(conditions)

        with self._conn() as conn:
            rows = conn.execute(
                f"""
                SELECT request_id, query, sector, confidence, escalated,
                       input_passed, output_passed, total_latency_ms, created_at
                FROM audit_log
                WHERE {where_sql}
                ORDER BY created_at ASC
                LIMIT ?
                """,
                params + [safe_limit],
            ).fetchall()
        return [dict(r) for r in rows]

    # ─── Metrics Aggregation ──────────────────────────────────────────

    def get_metrics(self, since: str) -> dict:
        """Compute aggregate metrics from audit_log since a given timestamp."""
        if self.use_supabase:
            with self._pg_conn() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        """SELECT
                            COUNT(*) as total_queries,
                            AVG(total_latency_ms) as avg_latency_ms,
                            AVG(confidence) as avg_confidence,
                            SUM(CASE WHEN escalated = TRUE THEN 1 ELSE 0 END) as escalated_count,
                            SUM(CASE WHEN input_passed = FALSE OR output_passed = FALSE THEN 1 ELSE 0 END) as rejected_count,
                            PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY total_latency_ms) as p95_latency_ms
                        FROM audit_log WHERE created_at >= %s""",
                        (since,),
                    )
                    metrics = dict(cur.fetchone())

                    cur.execute(
                        """SELECT sector, COUNT(*) as cnt FROM audit_log
                           WHERE created_at >= %s AND sector IS NOT NULL
                           GROUP BY sector ORDER BY cnt DESC""",
                        (since,),
                    )
                    sector_rows = cur.fetchall()
                    metrics["sector_distribution"] = {r["sector"]: r["cnt"] for r in sector_rows}

                    cur.execute(
                        """SELECT agent_used, COUNT(*) as cnt FROM audit_log
                           WHERE created_at >= %s AND agent_used IS NOT NULL
                           GROUP BY agent_used ORDER BY cnt DESC""",
                        (since,),
                    )
                    agent_rows = cur.fetchall()
                    metrics["agent_distribution"] = {r["agent_used"]: r["cnt"] for r in agent_rows}

            metrics["total_queries"] = int(metrics.get("total_queries") or 0)
            metrics["escalated_count"] = int(metrics.get("escalated_count") or 0)
            metrics["rejected_count"] = int(metrics.get("rejected_count") or 0)
            return metrics

        with self._conn() as conn:
            row = conn.execute(
                """SELECT
                    COUNT(*) as total_queries,
                    AVG(total_latency_ms) as avg_latency_ms,
                    AVG(confidence) as avg_confidence,
                    SUM(CASE WHEN escalated = 1 THEN 1 ELSE 0 END) as escalated_count,
                    SUM(CASE WHEN input_passed = 0 OR output_passed = 0 THEN 1 ELSE 0 END) as rejected_count
                FROM audit_log WHERE created_at >= ?""",
                (since,)
            ).fetchone()

            metrics = dict(row)

            # P95 latency
            p95_row = conn.execute(
                """SELECT total_latency_ms FROM audit_log
                   WHERE created_at >= ? AND total_latency_ms IS NOT NULL
                   ORDER BY total_latency_ms ASC""",
                (since,)
            ).fetchall()
            if p95_row:
                idx = int(len(p95_row) * 0.95)
                idx = min(idx, len(p95_row) - 1)
                metrics["p95_latency_ms"] = p95_row[idx]["total_latency_ms"]
            else:
                metrics["p95_latency_ms"] = None

            # Sector distribution
            sector_rows = conn.execute(
                """SELECT sector, COUNT(*) as cnt FROM audit_log
                   WHERE created_at >= ? AND sector IS NOT NULL
                   GROUP BY sector ORDER BY cnt DESC""",
                (since,)
            ).fetchall()
            metrics["sector_distribution"] = {r["sector"]: r["cnt"] for r in sector_rows}

            # Agent distribution
            agent_rows = conn.execute(
                """SELECT agent_used, COUNT(*) as cnt FROM audit_log
                   WHERE created_at >= ? AND agent_used IS NOT NULL
                   GROUP BY agent_used ORDER BY cnt DESC""",
                (since,)
            ).fetchall()
            metrics["agent_distribution"] = {r["agent_used"]: r["cnt"] for r in agent_rows}

        return metrics

    # ─── Cleanup ──────────────────────────────────────────────────────

    def cleanup_old_records(self) -> int:
        """Delete audit records older than AUDIT_RETENTION_DAYS. Returns count deleted."""
        cutoff = (datetime.now(timezone.utc) - timedelta(days=AUDIT_RETENTION_DAYS)).isoformat()

        if self.use_supabase:
            with self._pg_conn() as conn:
                with conn.cursor() as cur:
                    cur.execute(
                        "DELETE FROM audit_log WHERE created_at < %s", (cutoff,)
                    )
                    deleted = cur.rowcount
                conn.commit()
            return deleted

        with self._conn() as conn:
            cursor = conn.execute(
                "DELETE FROM audit_log WHERE created_at < ?", (cutoff,)
            )
        return cursor.rowcount

    # ─── Stats ────────────────────────────────────────────────────────

    def count_audit_records(self) -> int:
        if self.use_supabase:
            with self._pg_conn() as conn:
                with conn.cursor() as cur:
                    cur.execute("SELECT COUNT(*) AS cnt FROM audit_log")
                    return int(cur.fetchone()["cnt"])

        with self._conn() as conn:
            return conn.execute("SELECT COUNT(*) FROM audit_log").fetchone()[0]
