// Mock data for Shahem Intelligence Platform

export const MINISTRIES = [
  "Ministry of Digital Economy & Entrepreneurship",
  "Ministry of Justice",
  "Ministry of Health",
  "Ministry of Finance",
  "Ministry of Interior",
  "Ministry of Labour",
  "Ministry of Education",
  "Ministry of Agriculture",
  "Ministry of Energy & Mineral Resources",
  "Ministry of Foreign Affairs",
  "Ministry of Planning & International Cooperation",
  "Ministry of Water & Irrigation",
  "Ministry of Transport",
  "Ministry of Tourism & Antiquities",
  "Ministry of Public Works & Housing",
];

export const MOCK_TICKETS = [
  {
    id: "TKT-2024-0891",
    question: "What are the official procedures for registering a new business entity under the Companies Law in Jordan?",
    ministry: "Ministry of Digital Economy & Entrepreneurship",
    priority: "high",
    status: "open",
    confidence: 0.42,
    assignedTo: "Dr. Layla Al-Mansouri",
    createdAt: "2026-03-22T09:15:00Z",
    sla: "2026-03-24T09:15:00Z",
    domain: "Business Registration",
  },
  {
    id: "TKT-2024-0892",
    question: "Does the amended Labor Law No. 8 of 1996 apply to foreign workers under temporary work permits?",
    ministry: "Ministry of Labour",
    priority: "critical",
    status: "in_review",
    confidence: 0.38,
    assignedTo: "Ahmad Khalid Nassar",
    createdAt: "2026-03-22T08:00:00Z",
    sla: "2026-03-23T08:00:00Z",
    domain: "Labor Regulations",
  },
  {
    id: "TKT-2024-0893",
    question: "What healthcare coverage is provided under the Civil Insurance Law for government employees?",
    ministry: "Ministry of Health",
    priority: "medium",
    status: "pending",
    confidence: 0.44,
    assignedTo: null,
    createdAt: "2026-03-21T14:30:00Z",
    sla: "2026-03-25T14:30:00Z",
    domain: "Health Insurance",
  },
  {
    id: "TKT-2024-0894",
    question: "What are the penalties for late tax filing under the Income Tax Law No. 34 of 2014?",
    ministry: "Ministry of Finance",
    priority: "medium",
    status: "resolved",
    confidence: 0.41,
    assignedTo: "Rima Haddad",
    createdAt: "2026-03-20T11:00:00Z",
    sla: "2026-03-22T11:00:00Z",
    domain: "Taxation",
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: "DOC-001",
    title: "Civil Service Regulations 2023 — Amended Edition",
    ministry: "Ministry of Finance",
    type: "Regulation",
    language: "Arabic",
    pages: 84,
    chunks: 312,
    version: "v3.1",
    status: "published",
    uploadedAt: "2026-02-14T09:00:00Z",
    qualityScore: 0.94,
    tags: ["civil-service", "employment", "public-sector"],
  },
  {
    id: "DOC-002",
    title: "Labor Law No. 8 of 1996 — Consolidated Text",
    ministry: "Ministry of Labour",
    type: "Law",
    language: "Arabic",
    pages: 56,
    chunks: 218,
    version: "v2.4",
    status: "published",
    uploadedAt: "2026-01-28T14:00:00Z",
    qualityScore: 0.97,
    tags: ["labor", "employment-rights", "workers"],
  },
  {
    id: "DOC-003",
    title: "Investment Promotion Law — English Translation",
    ministry: "Ministry of Planning & International Cooperation",
    type: "Law",
    language: "English",
    pages: 38,
    chunks: 156,
    version: "v1.2",
    status: "processing",
    uploadedAt: "2026-03-18T10:15:00Z",
    qualityScore: 0.88,
    tags: ["investment", "economic", "foreign-affairs"],
  },
  {
    id: "DOC-004",
    title: "Public Procurement Guidelines — Government Contracts",
    ministry: "Ministry of Finance",
    type: "Guideline",
    language: "Arabic",
    pages: 102,
    chunks: 445,
    version: "v1.0",
    status: "processing",
    uploadedAt: "2026-03-22T08:30:00Z",
    qualityScore: null,
    tags: ["procurement", "government-contracts", "tenders"],
  },
  {
    id: "DOC-005",
    title: "Healthcare Information Policy Framework 2024",
    ministry: "Ministry of Health",
    type: "Policy",
    language: "Arabic",
    pages: 71,
    chunks: 289,
    version: "v2.0",
    status: "published",
    uploadedAt: "2026-02-01T11:00:00Z",
    qualityScore: 0.91,
    tags: ["health", "data-governance", "patient-rights"],
  },
];

export const MOCK_USERS = [
  { id: "U001", name: "Ahmad Youssef Al-Khalidi", email: "a.khalidi@moj.gov.jo", role: "Expert Reviewer", ministry: "Ministry of Justice", status: "active", lastActive: "2026-03-22T10:45:00Z" },
  { id: "U002", name: "Rima Farid Haddad", email: "r.haddad@mol.gov.jo", role: "Knowledge Curator", ministry: "Ministry of Labour", status: "active", lastActive: "2026-03-22T09:30:00Z" },
  { id: "U003", name: "Dr. Layla Ahmad Al-Mansouri", email: "l.mansouri@moh.gov.jo", role: "Expert Reviewer", ministry: "Ministry of Health", status: "active", lastActive: "2026-03-21T16:00:00Z" },
  { id: "U004", name: "Khalid Ibrahim Nassar", email: "k.nassar@mof.gov.jo", role: "Executive", ministry: "Ministry of Finance", status: "active", lastActive: "2026-03-22T11:20:00Z" },
  { id: "U005", name: "Sara Mohammed Al-Zu'bi", email: "s.zubi@moict.gov.jo", role: "System Admin", ministry: "Ministry of Digital Economy", status: "active", lastActive: "2026-03-22T12:00:00Z" },
  { id: "U006", name: "Omar Faisal Qasim", email: "o.qasim@mayor.gov.jo", role: "End User", ministry: "Municipality of Amman", status: "inactive", lastActive: "2026-03-15T09:00:00Z" },
];

export const MOCK_CHAT_MESSAGES = [
  {
    id: "msg-1",
    role: "user",
    content: "What are the requirements for a foreign investor to establish a company in Jordan under the Investment Law?",
    timestamp: "2026-03-22T10:00:00Z",
  },
  {
    id: "msg-2",
    role: "assistant",
    content: `Based on the **Investment Law No. 30 of 2014** and its amendments, foreign investors wishing to establish a company in Jordan must meet the following requirements:\n\n**1. Minimum Capital Requirements**\nForeign investors are generally required to bring in a minimum capital of **JD 50,000** for most business categories, unless a specific sector specifies otherwise [1].\n\n**2. Permitted Ownership Structures**\nForeign nationals may own up to **100% of a company's shares** in most sectors, with certain restrictions in:\n- Land ownership (limited to leaseholds in some zones)\n- Media and publishing\n- Professional services requiring Jordanian licensing [2]\n\n**3. Registration Process**\nThe entity must be registered with the:\n- Companies Control Department (CCD) under the Ministry of Industry, Trade & Supply\n- Investment Commission of Jordan (ICJ) if benefits are being sought [1][3]\n\n**4. Required Documents**\n- Authenticated articles of association\n- Proof of authorized capital deposit\n- Certified copies of investors' passports\n- Business plan summary (for incentive applications)\n\n**5. Investment Zones**\nEstablishment in a **Special Economic Zone** or **Development Zone** may offer additional tax incentives under separate regulations [3].`,
    sources: [
      { id: "src-1", title: "Investment Law No. 30 of 2014", ministry: "Ministry of Planning", page: 4, relevance: 0.96 },
      { id: "src-2", title: "Companies Law No. 22 of 1997", ministry: "Ministry of Justice", page: 12, relevance: 0.91 },
      { id: "src-3", title: "Investment Zones Bylaw 2018", ministry: "Ministry of Finance", page: 7, relevance: 0.87 },
    ],
    confidence: 0.89,
    mode: "thinking",
    timestamp: "2026-03-22T10:00:08Z",
  },
];
